config/routes.rb
Rails.application.routes.draw do

  match '/admins/sign_up', to: 'stat_pages#signup', via: 'get'
  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  root 'stat_pages#home'

  resources :albums

  resources :pictures

  resources :pies
  resources :cakes
  resources :candies
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  dragonfly_accessor :image
  has_many :pictures
  validates :meta_title, presence: true, uniqueness: true, :length => { :maximum => 60 }
  validates :meta_description, presence: true, uniqueness: true, :length => { :maximum => 150 }
end

app/models/cake.rb
class Cake < ActiveRecord::Base
  dragonfly_accessor :cakeimage
end

app/models/candy.rb
class Candy < ActiveRecord::Base
  dragonfly_accessor :candyimage
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  dragonfly_accessor :picimage
  belongs_to :album
end

app/models/pie.rb
class Pie < ActiveRecord::Base
  dragonfly_accessor :pieimage
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  respond_to :html, :xml, :json, :js

  def index
  	@albums = Album.all
    
  end

  before_action :up_page, only: :show

  def show
  	@album = Album.find(params[:id])
  	@pictures = @album.pictures
    @meta_title = @album.meta_title
    @meta_description = @album.meta_description
    @keywords = @album.keywords
  end

  private

  def album_params
  	params.require(:album).permit(:name, :description, :image)
  end

  def up_page 
   session[:page] = case 
                   when params[:new_req] then session[:page]+1
                   when params[:page] then params[:page]
                   else 1
  
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  def index
  	@cakes = Cake.all
  	@meta_title        = ""
    @meta_description  = ""
    @keywords          = ""
  end
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  def index
  	@candies = Candy.all
  	@meta_title        = ""
    @meta_description  = ""
    @keywords          = ""
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all.reverse   
  end

  def show
  	@picture = Picture.find(params[:id])
  end

  private

  def picture_params
  	params.require(:picture).permit(:pic_name, :pic_description, :picimage)
  end
end

app/controllers/pies_controller.rb
class PiesController < ApplicationController
  def index
  	@pies = Pie.all
  	@meta_title        = ""
    @meta_description  = ""
    @keywords          = ""
  end
end

app/controllers/stat_pages_controller.rb
class StatPagesController < ApplicationController

  def home
    @albums = Album.all
    @meta_title        = "Мастерская сладостей Яны Мартыновой"
    @meta_description  = "Мастерская сладостей Яны Мартыновой"
    @keywords          = ""
  end

  def signup
    redirect_to '/404'
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/pies_helper.rb
module PiesHelper
end

app/helpers/stat_pages_helper.rb
module StatPagesHelper
end

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Список всех альбомов здесь!</p>



<div>
<% @albums.each do |album| %>

  <p><%= album.name %></p>
  <p><%= album.description %></p>

<p><% if album.image_stored? %>
    <%= image_tag album.image.url, height: 200 %>
<% else %>
    <%= image_tag 'no_image.png', height: 200 %>
<% end %></p>
<p><%= link_to 'Show', album %></p>

<% end %>
</div>

app/views/albums/show.html.erb
<!-- Galery -->
    <div class="main">
      <div class="container">
        <section class="gallery">
          <div class="title">
            <h2>Наши работы</h2>
          </div>
          <div class="frame-block-holder frame-block-holder--full">
            <div class="frame-decor">
              <img src="images/frame-top.png" alt="top-frame">
            </div>
            <div class="frame-block frame-block--full">
              <% @pictures.in_groups_of(3).each do |pictures| %>
              <% pictures.select! {|x| !x.nil?} %>
              <ul class="frame-block__images">
              	<% pictures.each do |picture| %>
                <li>
                  <% if picture.picimage_stored? %>
                    <%= link_to picture.picimage.remote_url, class: 'fancybox', rel: 'gallery', title: picture.pic_name do %><% end %>
                    <%=	image_tag picture.picimage.url, :class => 'image fit', alt: picture.pic_name %>
                  <% else %>
                    <%= image_tag 'no_image.png' %>
                  <% end %>
                  <!--<p><%= picture.pic_name %></p>-->
                  <!--<p><%= picture.pic_description %></p>-->
                </li>
                <% end %>
              </ul>
              <% end %>
            </div>
            <div class="frame-decor">
              <img src="images/frame-bottom.png" alt="bottom-frame">
            </div>
          </div>
        </section>
      </div>
    </div>

app/views/cakes/index.html.erb
    <div class="main">
      <div class="container">
        <section class="details">
          <div class="title">
            <h2>Начинки кексов</h2>
          </div>
          <div class="frame-block-holder frame-block-holder--full">
            <div class="frame-decor">
              <img src="images/frame-top.png" alt="top-frame">
            </div>
            <div class="frame-block frame-block--full">
              <% @cakes.in_groups_of(3).each do |cakes| %>
              <% cakes.select! {|x| !x.nil?} %>
              <ul class="frame-block__images">
                <% cakes.each do |cake| %>
                <li>
                  <% if cake.cakeimage_stored? %>
                    <%= link_to cake.cakeimage.remote_url, class: 'fancybox', rel: 'gallery', title: cake.cake_name do %><% end %>
                    <%= image_tag cake.cakeimage.url, :class => 'image fit', alt: cake.cake_name %>
                  <% else %>
                    <%= image_tag 'no_image.png' %>
                  <% end %>
                  <!--<p><%= cake.cake_name %></p>-->
                  <!--<p><%= cake.cake_description %></p>-->
                </li>
                <% end %>
              </ul>
              <% end %>
            <div class="frame-block__text">
                  <div class="image-content alignright">
                    <img src="images/icon-cake-1.png" alt="Cake">
                  </div>
                  <div class="text-content">
                      But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. 
                    Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.<br>
                     <br>
                    To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
                  </div>
              </div>
            </div>
            <div class="frame-decor">
              <img src="images/frame-bottom.png" alt="bottom-frame">
            </div>
          </div>
        </section>
      </div>
    </div>

app/views/candies/index.html.erb
    <div class="main">
      <div class="container">
        <section class="details">
          <div class="title">
            <h2>Candy Bar</h2>
          </div>
          <div class="frame-block-holder frame-block-holder--full">
            <div class="frame-decor">
              <img src="images/frame-top.png" alt="top-frame">
            </div>
            <div class="frame-block frame-block--full">
              <% @candies.in_groups_of(3).each do |candies| %>
              <% candies.select! {|x| !x.nil?} %>
              <ul class="frame-block__images">
                <% candies.each do |candy| %>
                <li>
                  <% if candy.candyimage_stored? %>
                    <%= link_to candy.candyimage.remote_url, class: 'fancybox', rel: 'gallery', title: candy.candy_name do %><% end %>
                    <%= image_tag candy.candyimage.url, :class => 'image fit', alt: candy.candy_name %>
                  <% else %>
                    <%= image_tag 'no_image.png' %>
                  <% end %>
                  <!--<p><%= candy.candy_name %></p>-->
                  <!--<p><%= candy.candy_description %></p>-->
                </li>
                <% end %>
              </ul>
              <% end %>
            <div class="frame-block__text">
                  <div class="image-content alignright">
                    <img src="images/icon-cake-1.png" alt="Cake">
                  </div>
                  <div class="text-content">
                      But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. 
                    Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.<br>
                     <br>
                    To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
                  </div>
              </div>
            </div>
            <div class="frame-decor">
              <img src="images/frame-bottom.png" alt="bottom-frame">
            </div>
          </div>
        </section>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title><%= @meta_title %></title>
  <meta name="description" content="<%= @meta_description %>" />
  <meta name="keywords" content="<%= @keywords %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!--[if lte IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>

<% if current_page?(root_path) %>
  <body>
<% else %>
  <body class="page">
<% end %>

	<div class="wrapper">
	<!-- Header -->
    <%= render 'shared/header' %>

  <!-- Main -->

<%= yield %>

	<!-- Footer -->
		<%= render 'shared/footer' %>

  </div>
</body>
</html>

app/views/pictures/index.html.erb
<h1>Pictures#index</h1>
<p>Find me in app/views/pictures/index.html.erb</p>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/pies/index.html.erb
    <div class="main">
      <div class="container">
        <section class="details">
          <div class="title">
            <h2>Начинки тортов</h2>
          </div>
          <div class="frame-block-holder frame-block-holder--full">
            <div class="frame-decor">
              <img src="images/frame-top.png" alt="top-frame">
            </div>
            <div class="frame-block frame-block--full">
              <% @pies.in_groups_of(3).each do |pies| %>
              <% pies.select! {|x| !x.nil?} %>
              <ul class="frame-block__images">
                <% pies.each do |pie| %>
                <li>
                  <% if pie.pieimage_stored? %>
                    <%= link_to pie.pieimage.remote_url, class: 'fancybox', rel: 'gallery', title: pie.pie_name do %><% end %>
                    <%= image_tag pie.pieimage.url, :class => 'image fit', alt: pie.pie_name %>
                  <% else %>
                    <%= image_tag 'no_image.png' %>
                  <% end %>
                  <!--<p><%= pie.pie_name %></p>-->
                  <!--<p><%= pie.pie_description %></p>-->
                </li>
                <% end %>
              </ul>
              <% end %>
            <div class="frame-block__text">
                  <div class="image-content alignright">
                    <img src="images/icon-cake-1.png" alt="Cake">
                  </div>
                  <div class="text-content">
                      But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. 
                    Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.<br>
                     <br>
                    To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
                  </div>
              </div>
            </div>
            <div class="frame-decor">
              <img src="images/frame-bottom.png" alt="bottom-frame">
            </div>
          </div>
        </section>
      </div>
    </div>

app/views/shared/_footer.html.haml
/ Footer
%footer
  .container
    .title#contacts
      %h2 Контакты
    .contacts.frame-block-holder.frame-block-holder--small
      .frame-decor
        %img{:alt => "top-frame", :src => "images/frame-s-top.png"}
      .frame-block.frame-block--small
        %table.contacts-t
          %tr
            %td Тел.
            %td
              %a{:href => "tel: +38-093-000-00-00"} +38 093 000 00 00
          %tr
            %td
            %td
              %a{:href => "tel: +38-098-000-00-00"} +38 098 000 00 00
          %tr
            %td e-mail:
            %td
              %a{:href => "mailto: mail@mail.com"} mail@mail.com
      .frame-decor
        %img{:alt => "bottom-frame", :src => "images/frame-s-bottom.png"}

app/views/shared/_header.html.haml
/ Header
%header
  .logo
    %a{:href => "#"}
      %img{:alt => "Logo", :src => "images/logo.png"}/
  .nav-holder
    %nav.nav
      .container
        .nav-wrapper
          %ul.main-nav
            %li= link_to 'Наши работы', root_path(anchor: 'our_works')
            %li= link_to 'Оформить заказ', root_path(anchor: 'zakaz')
            %li= link_to 'Контакты', root_path(anchor: 'contacts')
          %ul.soc-nav
            %li
              %a{:href => "http://vk.com/club53389244"}
                %i.icon-facebook-square
            %li
              %a{:href => "http://ok.ru/tortkharkov"}
                %i.icon-odnoklassniki-square
            %li
              %a{:href => "https://www.facebook.com/yanamdontsova"}
                %i.icon-vkontakte

app/views/stat_pages/contacts.html.erb
<section>
	<div class="container">
		<p>Телефоны:</p>
		<p>E-mail:</p>
		<p>Адрес:</p>
		<p>Также для связи вы сожете использовать форму внизу сайта. Мы ответим вам в самое ближайшее время</p>
	</div>
</section>

app/views/stat_pages/home.html.erb
<!-- Main -->
    <div class="main">
      <div class="container">
        <section class="welcome">
          <div class="welcome__image">
            <img src="images/welcome.png" alt="Добро пожаловать с студию Яны Мартыновой">
          </div>
          <div class="title">
            <h2>Сладкое искусство</h2>
          </div>
          <div class="benefits">
            <ul class="benefits__list">
              <li><%= link_to image_tag("/images/icon-cake-1.png"), pies_path %></li>
              <li><%= link_to image_tag("/images/icon-cake-2.png"), cakes_path %></li>
              <li><%= link_to image_tag("/images/icon-cake-3.png"), candies_path %></li>
            </ul>
          </div>
        </section>
        <section class="our-works">
          <div class="title" id="our_works">
            <h2>Наши работы</h2>
          </div>
          <div class="frame-block-holder frame-block-holder--full">
            <div class="frame-decor">
              <img src="images/frame-top.png" alt="top-frame">
            </div>
            <div class="frame-block frame-block--full">
              <div class="frame-block__text">
                Цену на торт вычисляю индивидуально в зависимости от начинки и сложности украшени   й, от 160 грн/кг. 
                Торт без мастики от 200 грн/кг.
                Капкейки - от 20-50 грн\шт.
                Расписное Печенье от 10 грн\шт (около 6–8 см), пряники от 20 грн\шт. Печенье 11 см около 30грн\ шт. Упаковка каждого печенья в пакетик с бантиком +1 грн за шт.
                НАЧИНКИ тортов смотрите здесь https://vk.com/album-53389244_173924072<br>
                <br>
                Заказы принимаются не позднее 4 дней до торжества .Заказы принимаются не позднее 4 дней до торжества Заказы принимаются не позднее 4 дней до торжества (при условии, что дата не будет уже занята). Срочные заказы оговариваются отдельно и подлежат дополнительной оплате.
              </div>
              <ul class="frame-block__images">
              	<% @albums.each do |album| %>
                <li>
                  <% if album.image_stored? %>
                    <%= link_to album do %><% end %>
                      <div class="image-hover">      
                        <i class="icon-camera"></i>
                      </div>
                    <%= image_tag album.image.url %>
                  <% else %>
                    <%= image_tag 'no_image.png' %>
                  <% end %>
                </li>
                <% end %>
              </ul>
            </div>
            <div class="frame-decor">
              <img src="images/frame-bottom.png" alt="bottom-frame">
            </div>
          </div>
        </section>
        <section class="order">
          <div class="title" id="zakaz">
            <h2>Оформить заказ</h2>
          </div>
          <div class="order-content">
            <div class="frame-block-holder frame-block-holder--half">
              <div class="frame-decor">
                <img src="images/frame-h-top.png" alt="top-frame">
              </div>
              <div class="frame-block frame-block--half">
              Цену на торт вычисляю индивидуально в зависимости от начинки и сложности украшени   й, от 160 грн/кг. 
              Торт без мастики от 200 грн/кг.
              Капкейки - от 20-50 грн\шт.
              Расписное Печенье от 10 грн\шт (около 6–8 см), пряники от 20 грн\шт. Печенье 11 см около 30грн\ шт. Упаковка каждого печенья в пакетик с бантиком +1 грн за шт.
              </div>
              <div class="frame-decor">
                <img src="images/frame-h-bottom.png" alt="bottom-frame">
              </div>
            </div>
            <div class="image-content">
              <img src="images/order-bg.png" alt="Закажите вкусняшку">
            </div>
          </div>
        </section>
      </div>
    </div>
<!-- Footer -->    